apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: s2i-dpdk-centos7
    app.kubernetes.io/component: s2i-dpdk-centos7
    app.kubernetes.io/instance: s2i-dpdk-centos7
  name: s2i-dpdk-centos7
  namespace: dpdk
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: s2i-dpdk-centos7:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: test/test-app
    git:
      uri: https://github.com/SchSeba/s2i-dpdk-centos7.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: quay.io/schseba/dpdk-centos7:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
