apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: s2i-dpdk-centos7
    app.kubernetes.io/component: s2i-dpdk-centos7
    app.kubernetes.io/instance: s2i-dpdk-centos7
  name: s2i-dpdk-centos7-testpmd
  namespace: dpdk-testing
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: s2i-dpdk-centos7
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: s2i-dpdk-centos7
      annotations:
        k8s.v1.cni.cncf.io/networks: dpdk-testing/dpdk-network
    spec:
      serviceAccount: deployer
      serviceAccountName: deployer
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/dpdk/s2i-dpdk-centos7
          securityContext:
            capabilities:
              add: ["IPC_LOCK","NET_ADMIN","NET_RAW"]
          imagePullPolicy: Always
          env:
            - name: RUN_TYPE
              value: "testpmd"
          name: s2i-dpdk-centos7
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: "4"
              hugepages-1Gi: 8Gi
              memory: 1000Mi
            requests:
              cpu: "4"
              hugepages-1Gi: 8Gi
              memory: 1000Mi
          volumeMounts:
            - mountPath: /mnt/huge
              name: hugepage
      dnsPolicy: ClusterFirst
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - s2i-dpdk-centos7
        from:
          kind: ImageStreamTag
          name: s2i-dpdk-centos7:latest
          namespace: dpdk
      type: ImageChange
