---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: dpdk-s2i-base
  namespace: dpdk-testing
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: dpdk-base
    app.kubernetes.io/component: dpdk-base
    app.kubernetes.io/instance: dpdk-base
  name: dpdk-base
  namespace: dpdk-testing
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  output:
    to:
      kind: ImageStreamTag
      name: dpdk-s2i-base:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/SchSeba/s2i-dpdk-centos7.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: "DockerImage"
        name: "openshift/base-centos7"
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
